### ISSUE TITLE
cannot import name 'SVDLinear4bit' from 'deep_training.nlp.layers.petl.lora.adalora'

### ISSUE THREAD

**Issue by dark-lake** [thu-coai/BPO#20]
deep-training            0.2.4
执行python data_util.py报错

**Comment by dark-lake** [comment]
(bpo1) root@master-W780-G20:/opt/module/bpo1/src/training# python data_utils_zh.py
[2024-03-01 16:12:45,239] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/opt/module/bpo1/src/training/data_utils_zh.py", line 13, in <module>
    from aigc_zoo.model_zoo.llm.llm_model import PetlArguments, LoraConfig, PromptArguments
  File "/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/aigc_zoo/model_zoo/llm/llm_model.py", line 9, in <module>
    from ...weight.modelweighter import *
  File "/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/aigc_zoo/weight/modelweighter.py", line 11, in <module>
    from deep_training.trainer.pl.modelweighter import *
  File "/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/deep_training/trainer/pl/modelweighter.py", line 12, in <module>
    from ...nlp.models.petl.prompt import PromptLearningConfig, PromptModel,PromptArguments,get_prompt_model
  File "/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/deep_training/nlp/models/petl/__init__.py", line 5, in <module>
    from .lora.petl_model import PetlModel,LoraModule,LoraConfig,AdaLoraConfig,IA3Config,PetlArguments
  File "/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 19, in <module>
    from .adalora_model import AdaLoraModule
  File "/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/adalora_model.py", line 12, in <module>
    from ....layers.petl.lora.adalora import RankAllocator, SVDLinear, SVDLinear4bit, SVDQuantLinear, AdaLoraLayer
ImportError: cannot import name 'SVDLinear4bit' from 'deep_training.nlp.layers.petl.lora.adalora' (/opt/module/anaconda3/envs/bpo1/lib/python3.10/site-packages/deep_training/nlp/layers/petl/lora/adalora.py)

**Comment by dark-lake** [comment]
改为deep-training==0.2.6,不会报这个问题了
